"Cumplimiento de ticket"
Tecnologer/ToDoList pull request #8
Opened 2021-09-02 02:33 UTC by oscarCR19

Se asignaron las propiedades adecuadas para una futura integración con bases de datos.

2021-09-02 17:31 UTC, Tecnologer commented
tus commits deben de ser descriptivos, la idea es que veas el commit y puedas tener un idea que se modifico en ese ticket

2021-09-02 17:32 UTC, Tecnologer commented
el merge debe de ser hacia `master`, porque de la manera que tu lo definiste indica que llevaras los cambios de `master` hacia tu branch, cuando se requiere lo contrario

![image](https://user-images.githubusercontent.com/8458967/131890132-701583a0-6ecf-4ce6-b011-f8d6e794bc37.png)

2021-09-02 17:33 UTC, Tecnologer commented on ToDoListSrc/src/todolist/ToDoList.java
> +
mira, tu commit dice que incluye los cambios del ticket, pero en este archivo cambio el formato de los tabs, y pues eso no lo dice tu commit

2021-09-02 17:40 UTC, Tecnologer requested changes

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/ToDoList.java
> -            usuario.completarTarea(descripcion,fecha);
la fecha no debe ser un argumento, debe de ser calculada antes de mandarla a la db

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/modelos/Tarea.java
> -    private int IDUsuario;
la nomenclatura standard es nombrar las relaciones primero la entidad y luego a la propiedad que hace referencia, es decir, deberia de ser `UsuarioID`

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/modelos/Tarea.java
> -    private Date fechaInicio;
Hay que usar fechas con tiempo y zona horaria, el tipo recomendado aqui seria [`OffsetDateTime`](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#:~:text=OffsetDateTime%20is%20an%20immutable%20representation,be%20stored%20in%20an%20OffsetDateTime%20.)

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/modelos/Tarea.java
> -    public Tarea(String descripcion, int idUsuario,Date fechaInicio) {
igual, la fecha inicio es cuando se creo la tarea, no la determina el usuario, debe ser interna

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/modelos/Tarea.java
> -    public void setIDUsuario(int IDUsuario) {
el id debe ser readonly, es decir, no debe cambiar una vez creado el usuario, por lo que deberia de recibirse unicamente en el constructor

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/modelos/Tarea.java
> -    public void setFechaInicio(Date fechaInicio) {
las fechas tambien debe de ser readonly, no deberian poder modificarse

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/modelos/Usuario.java
> -    public void setID(int ID) {
el id debe ser readOnly

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/src/todolist/modelos/Usuario.java
> -    public void completarTarea(String descripcion,Date fechaFinalizacion) throws Exception {
mismo detalle de la fecha, debe de ser calculada internamente

2021-09-02 17:40 UTC, Tecnologer commented on ToDoListSrc/test/UserTests.java
> -       // assertThrows(Exception.class, () -> {
por que se quito esta prueba?

2021-09-06 01:43 UTC, oscarCR19 commented on ToDoListSrc/src/todolist/ToDoList.java
> -            usuario.completarTarea(descripcion,fecha);
podría explicarme un poco más sobre este punto?

2021-09-06 01:56 UTC, oscarCR19 commented on ToDoListSrc/test/UserTests.java
> -       // assertThrows(Exception.class, () -> {
La prueba se tuvo que comentar para que no marcara error, ya que con la integracion de los cambios hay que tambien añadir nuevas pruebas

2021-09-07 20:42 UTC, Tecnologer commented on ToDoListSrc/src/todolist/ToDoList.java
> -            usuario.completarTarea(descripcion,fecha);
es un valor propio de la tarea, un valor interno de solo lectura, entonces cuando la tarea se marque como completada al mismo tiempo se tiene que asignar el valor de `datetime` cuando eso sucedio

2021-09-07 20:43 UTC, Tecnologer commented on ToDoListSrc/test/UserTests.java
> -       // assertThrows(Exception.class, () -> {
ok, solo que no se olvide agregarla al hacer el commit

2021-09-10 03:27 UTC, oscarCR19 commented on ToDoListSrc/src/todolist/ToDoList.java
> -            usuario.completarTarea(descripcion,fecha);
Listo he tomado la idea.
Gracias

2021-10-02 02:49 UTC, Tecnologer commented
iniciamos desde master

2021-10-02 02:49 UTC, closed without merging